---
label: Default
hide_body: false
fields:
- type: text
  name: title
  label: title
  description: 'The article title '
  config:
    required: true
- name: permalink
  type: text
  config:
    required: false
  label: permalink
  description: the url
- type: textarea
  name: description
  label: Description
  description: A description for social networks
  config:
    required: true
- type: file
  name: header-img
  label: header image
  description: Header Image
- name: paginate
  default: true
  label: Paginate
  type: boolean
  hidden: true
- name: comments
  default: true
  label: Comments
  type: boolean
  hidden: true
- name: author
  default: musikele
  label: Author
  type: text
  hidden: true
- name: category
  type: select
  label: Category
  description: Category
  hidden: false
  config:
    options:
    - Italiano
    - English
  default: Italiano
- name: tags
  type: tag_list
  label: Tags
  description: tags
- name: layout
  type: text
  hidden: true
  label: layout
  description: the layout
  default: post
  config:
    required: true
- type: datetime
  default: now
  label: date
  name: date
  config:
    date_format: DD/MM/YYYY
    required: true
    display_utc: true
    export_format: YYYY-MM-DD
    time_format: " "
pages:
- _posts/2017-02-05-quali-sono-gli-svantaggi-nel-lavorare-da-casa.md
- _posts/2017-02-10-hey-javascript-function-take-this.md
- _posts/2017-02-25-the-javascript-event-loop-for-dummies.md
- _posts/2017-03-01-quando-l-azienda-non-paga-gli-stipendi.md
- _posts/2017-03-13-js-promises-description-pros-cons-of-this-es6-construct.md
- _posts/2017-03-14-two-easy-ways-perform-get-requests-in-nodejs.md
- _posts/2017-03-21-l-inglese-tra-italiani-a-lavoro-e-una-scelta-sbagliata.md
- _posts/2017-03-23-deploy-a-nodejs-app-on-heroku-in-less-than-1-minute.md
- _posts/2017-03-28-become-a-test-expert-in-nodejs-with-these-tricks.md
- _posts/2017-04-08-all-my-articles-about-testing-in-javascript-in-one-post.md
- _posts/2017-05-22-i-colloqui-di-lavoro-nelle-big.md
- _posts/2017-07-17-recensione-del-libro-codice-montemagno.md
- _posts/2017-08-09-vacanze-guida-alla-val-d-aosta-con-un-neonato.md
- _posts/2017-08-18-due-tre-opinioni-sul-growth-hacking-da-uno-che-non-ha-mai-fatto-nulla-di-marketing.md
- _posts/2017-09-19-come-capire-il-bitcoin-le-funzioni-crittografiche.md
- _posts/2017-10-03-viviamo-tutti-in-una-grande-simulazione-aliena-sembra-di-no.md
- _posts/2017-10-30-cryptomining-and-websites-how-long-will-be-tolerated.md
- _posts/2017-11-14-not-a-number-when-javascript-gets-crazy.md
- _posts/2017-11-17-why-nan.md
- _posts/2017-11-20-growth-hacker-cos-e-intervista-a-raffaele-gaito.md
- _posts/2017-12-01-batman-ha-ispirato-il-comic-sans-storia-di-un-font-che-tutti-odiano.md
- _posts/2017-12-04-alla-scoperta-di-vue-js.md
- _posts/2017-12-04-dovrei-partecipare-al-programma-erasmus.md
- _posts/2018-01-06-essere-programmatori-e-vivere-di-progetti-propri.md
- _posts/2018-01-07-e-importante-conoscere-come-sono-fatte-le-librerie-che-usiamo.md
- _posts/2018-01-09-i-trend-javascript-del-2018.md
- _posts/2018-01-12-la-mia-esperienza-col-test-driven-development.md
- _posts/2018-01-18-perche-la-green-card-e-una-lotteria.md
- _posts/2018-02-02-risultati-sondaggio-i-programmatori-e-i-corsi-di-formazione.md
- _posts/2018-02-18-un-giro-nell-universo-react.md
- _posts/2018-02-25-cosa-ho-imparato-dai-miei-sbagli-ossia-consigli-per-i-giovani-laureandi.md
- _posts/2018-04-05-come-realizzare-un-form-esterno-es-assistenza-che-manda-dati-a-magnews.md
- _posts/2018-04-05-un-programmatore-dovrebbe-continuare-a-programmare-nel-suo-tempo-libero.md
- _posts/2018-04-16-ode-ai-libri-di-carta.md
- _posts/2018-04-24-startup-weekend-salerno-2018.md
- _posts/2018-05-06-proteggi-le-tue-applicazioni-express-con-helmetjs.md
- _posts/2018-06-05-libri-sei-proprio-il-mio-typo-la-vita-segreta-dei-font.md
- _posts/2018-06-18-get-the-list-of-files-blocked-by-a-process-in-linux.md
- _posts/2018-07-10-designing-the-documentation-for-a-tech-product.md
- _posts/2018-07-22-laravel-style-config-in-nodejs.md
- _posts/2018-08-22-ma-cosa-intendete-per-testing-una-breve-introduzione-al-testing-software.md
- _posts/2018-09-03-some-things-you-may-not-know-about-object-oriented-javascript-es6.md
- _posts/2018-09-04-symbols-iterators-in-javascript.md
- _posts/2018-09-19-Javascript-chiamare-funzioni-senza-usare-parentesi-(what!).md
- _posts/2018-10-15-dovrei-imparare-ruby-on-rails-o-nodejs.md
- _posts/2018-10-25-docker-cheatsheet.md
- _posts/2018-10-29-the-easiest-way-to-understand-javascript-generators.md
- _posts/2018-11-05-inspiring-tech-people-to-follow-nicholas-c-zakas.md
- _posts/2018-11-17-what-i-learned-by-writing-my-first-npm-module.md
- _posts/2018-12-12-remembering-the-bad-bad-days-of-browser-wars.md
- _posts/2019-02-12-how-ads-are-loaded-so-fast-the-command-queue-pattern.md
- _posts/2019-03-23-what-s-the-difference-between-browserify-and-webpack.md
- _posts/2019-04-03-ssh-cheatsheet-from-zero-to-hero.md
- _posts/2019-06-13-i-work-remote-i-do-two-video-calls-per-day.md
- _posts/2019-06-27-typescript-babel-webpack-eslint-my-configuration.md
- _posts/2019-08-02-detect-network-issues-to-urls.md
- _posts/2019-08-17-what-is-the-difference-between-var-let-and-const-in-javascript.md
- _posts/2019-10-20-how-internet-ads-work.md
- _posts/2019-10-27-tips-tricks-from-my-linux-experience.md
- _posts/2019-11-21-thinking-about-your-customer-like-a-ceo.md
- _posts/2019-12-09-merge-requests-vs-pair-programming.md
- _posts/2020-01-30-a-review-of-the-book-the-phoenix-project.md
- _posts/2020-02-06-microsoft-surface-go-more-than-a-tablet.md
- _posts/2020-05-02-i-wish-i-had-my-quarantine.md
- _posts/2020-05-19-how-coronavirus-affected-my-life.md
- _posts/2020-05-25-saro-controcorrente-ma-a-me-piaceva-andare-in-ufficio.md
- _posts/2020-06-15-my-first-visual-studio-code-extension-create-link-to-git-server.md
- _posts/2020-09-16-how-to-read-and-write-from-stdin-and-stdout-in-go.md
- _posts/2020-10-09-book-what-if-serious-scientific-answers-to-absurd-hypothetical-questions.md
- _posts/2020-12-28-a-guide-to-mvc-frameworks.md
- _posts/2021-02-12-how-to-integrate-a-django_select2-component-in-django-admin.md
- _posts/2021-04-02-clickhouse-a-database-for-your-next-big-data-project.md
- _posts/2021-07-06-remotalypse-now-non-tutti-vogliono-tornare-in-ufficio.md
- _posts/customizing-django-admin.md
- _posts/just-enough-functional-programming-in-javascript.md
- _posts/just-enough-redis.md
- _posts/react-native.md
- _posts/some-opinions-on-clickhouse-db.md
